version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    allow:
      - dependency-type: 'production'
    ignore:
      - dependency-name: 'tldts-experimental'
      - dependency-name: '@sentry/browser'
    schedule:
      interval: 'daily'
      time: '07:00'
    reviewers:
      - 'smalluban'
      - 'chrmod'
    open-pull-requests-limit: 99
    groups:
      adblocker:
        patterns:
          - '@ghostery/adblocker*'
  - package-ecosystem: npm
    directory: '/'
    allow:
      - dependency-type: 'development'
      # 'tldts-experimental' and '@sentry/browser' update frequently, but we need to keep them up to date
      # for each release to the production, which happens at most once a week.
      - dependency-name: 'tldts-experimental'
      - dependency-name: '@sentry/browser'
    ignore:
      # Currently the wdio has a bug, which does not allow us to update it often
      - dependency-name: '@wdio/*'
    schedule:
      interval: 'weekly'
      time: '07:00'
    reviewers:
      - 'smalluban'
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
      wdio:
        patterns:
          - '@wdio/*'
      web-ext:
        patterns:
          - 'web-ext'
          - 'addon-linter'
    # Makes it possible to have another config. for the same dir.
    # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: main
