version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
    groups:
      wdio:
        patterns:
          - "@wdio/*"
      adblocker:
        patterns:
          - "@ghostery/adblocker*"
      web-ext:
        patterns:
          - "web-ext"
          - "addon-linter"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
