version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "extension-manifest-v3"
      - "packages/*"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
    reviewers:
      - smalluban
      - philipp-classen
      - chrmod
    labels:
      - "Dependencies"
