/**
 * Ghostery Browser Extension
 * https://www.ghostery.com/
 *
 * Copyright 2017-present Ghostery GmbH. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0
 */

import { wrapScriptletSource } from './wrap-scriptlet.js';

// Lets the e2e suite count executions and assert exactly-once injection.
export const TEST_SCRIPTLET_NAME = '__e2e-inc.js';

const TEST_SCRIPTLET = {
  func: function (globals, name) {
    self[name] = (self[name] || 0) + 1;
  },
};

const BANNER = `/* eslint-disable */
// Generated by scripts/generate-scriptlets.js — DO NOT EDIT.
// Each scriptlet func is wrapped with an in-document idempotency guard.`;

function emitEntry(name, entry, debug) {
  if (typeof entry.func !== 'function') {
    throw new Error(
      `[generate-scriptlets] expected "func" to be a function for scriptlet "${name}", got ${typeof entry.func}`,
    );
  }

  const key = JSON.stringify(name);
  const world = entry.world ? `\n  world: ${JSON.stringify(entry.world)},` : '';
  const aliases = (entry.aliases || [])
    .map((alias) => `\nSCRIPTLETS[${JSON.stringify(alias)}] = SCRIPTLETS[${key}];`)
    .join('');

  return `SCRIPTLETS[${key}] = {${world}
  func: ${wrapScriptletSource(entry.func.toString(), { debug, name })},
};${aliases}`;
}

export function generateScriptletsModule(source, { debug = false } = {}) {
  // The package repeats each entry under its aliases, canonical name first; dedupe by identity.
  const seen = new Set();
  const entries = [];
  for (const [name, entry] of Object.entries(source)) {
    if (seen.has(entry)) continue;
    seen.add(entry);
    entries.push([name, entry]);
  }

  if (debug) entries.push([TEST_SCRIPTLET_NAME, TEST_SCRIPTLET]);

  const blocks = entries.map(([name, entry]) => emitEntry(name, entry, debug));

  return `${BANNER}
const SCRIPTLETS = {};

${blocks.join('\n\n')}

export default SCRIPTLETS;
`;
}
