/**
 * Ghostery Browser Extension
 * https://www.ghostery.com/
 *
 * Copyright 2017-present Ghostery GmbH. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0
 */

import { wrapScriptletSource } from './wrap-scriptlet.js';

// Debug-build-only counting scriptlet: each run bumps `self[args[0]]`, letting
// the e2e spec assert exactly-once execution however many triggers fired.
export const TEST_SCRIPTLET_NAME = '__e2e-inc.js';

const TEST_SCRIPTLET = {
  func: function (scriptletGlobals, ...args) {
    self[args[0]] = (self[args[0]] || 0) + 1;
  },
};

const BANNER = `/* eslint-disable */
// Generated by scripts/generate-scriptlets.js — DO NOT EDIT.
// Each scriptlet func is wrapped with an in-document idempotency guard.`;

function emitEntry(name, entry, debug) {
  if (typeof entry.func !== 'function') {
    throw new Error(
      `[generate-scriptlets] expected "func" to be a function for scriptlet "${name}", got ${typeof entry.func}`,
    );
  }

  const lines = [`  aliases: ${JSON.stringify(entry.aliases || [])},`];
  if (entry.world) lines.push(`  world: ${JSON.stringify(entry.world)},`);
  lines.push(`  requiresTrust: ${!!entry.requiresTrust},`);
  lines.push(`  func: ${wrapScriptletSource(entry.func.toString(), { debug, name })},`);

  return `SCRIPTLETS[${JSON.stringify(name)}] = {\n${lines.join('\n')}\n};`;
}

export function generateScriptletsModule(source, { debug = false } = {}) {
  // The package expands aliases as extra keys on the same object, canonical name
  // first; dedupe by identity to recover the canonical entries in order.
  const seen = new Set();
  const entries = [];
  for (const [name, entry] of Object.entries(source)) {
    if (seen.has(entry)) continue;
    seen.add(entry);
    entries.push([name, entry]);
  }

  if (debug) entries.push([TEST_SCRIPTLET_NAME, TEST_SCRIPTLET]);

  const blocks = entries.map(([name, entry]) => emitEntry(name, entry, debug));

  return `${BANNER}
const SCRIPTLETS = {};

${blocks.join('\n\n')}

const scriptlets = {};
for (const [name, scriptlet] of Object.entries(SCRIPTLETS)) {
  scriptlets[name] = scriptlet;
  for (const alias of scriptlet.aliases) {
    scriptlets[alias] = scriptlet;
  }
}

export default scriptlets;
`;
}
