name: Lint & Test

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
    branches:
      - master
      - develop

jobs:
  check-pr-title-format:
    runs-on: ubuntu-20.04
    - uses: actions/setup-node@v2
      with:
      node-version: '10'
    steps:
      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build Licenses
        run: |
          node ./tools/licenses/fetchLicenses.js
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test

