/**
 * Ghostery Browser Extension
 * https://www.ghostery.com/
 *
 * Copyright 2017-present Ghostery GmbH. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0
 */

import { html, store } from 'hybrids';

import { WTM_PAGE_URL } from '/utils/urls.js';
import { shortDateFormatter, categories } from '/ui/labels.js';

import { MergedStats } from '/store/daily-stats.js';

const MONTH_IN_MS = 30 * 24 * 60 * 60 * 1000;
const DAY_IN_MS = 24 * 60 * 60 * 1000;
const now = Date.now();

function setDurationToLastMonth(host) {
  host.dateFrom = new Date(now - MONTH_IN_MS - DAY_IN_MS)
    .toISOString()
    .slice(0, 10);
  host.dateTo = new Date(now - DAY_IN_MS).toISOString().slice(0, 10);
}

function setDurationToYesterday(host) {
  host.dateFrom = new Date(now - DAY_IN_MS).toISOString().slice(0, 10);
  host.dateTo = host.dateFrom;
}

function toggleTrend(trend) {
  return (host) => {
    host.trends = host.trends.includes(trend)
      ? host.trends.filter((t) => t !== trend)
      : [...host.trends, trend];
  };
}

export default {
  dateFrom: '',
  dateTo: '',
  duration: {
    value: 'month',
    connect: setDurationToLastMonth,
    observe: (host, value) => {
      switch (value) {
        case 'month':
          setDurationToLastMonth(host);
          break;
        case 'yesterday':
          setDurationToYesterday(host);
          break;
      }
    },
  },
  mergedStats: store(MergedStats, {
    id: ({ dateFrom, dateTo }) => ({ dateFrom, dateTo }),
  }),
  trends: { value: ['pages', 'trackersBlocked', 'trackersModified'] },
  render: ({ duration, dateFrom, dateTo, mergedStats, trends }) => html`
    <template layout>
      <main
        layout="column padding:2 gap:5 margin:0:auto width:::1264px"
        layout@768px="padding:4"
      >
        <section layout="relative column gap:2 padding:2:0:0">
          <header layout="row items:center gap:1.5" translate="no">
            <ui-icon name="wtm-border"></ui-icon>
            <div layout="column">
              <ui-text type="label-l" color="tertiary" uppercase>
                Ghostery
              </ui-text>
              <ui-text type="display-m">WhoTracks.Me</ui-text>
            </div>
          </header>
          <ui-text type="body-l" mobile-type="body-m" color="secondary">
            This privacy report was generated by tracking the trackers in a
            browser protected by Ghostery. The statistics here provide
            transparency about web tracking. To learn more about how Ghostery
            keeps its community safe, visit
            <span>
              ${html`<ui-text
                type="label-l"
                mobile-type="label-m"
                color="brand-primary"
                translate="no"
                layout="inline"
              >
                <a href="https://www.ghostery.com/whotracksme">
                  ghostery.com/whotracksme</a
                ></ui-text
              >`}</span
            >.
          </ui-text>
          <div layout="row content:end gap" layout@768px="absolute top right">
            <ui-button disabled>
              <button>Print to PDF</button>
            </ui-button>
            <div layout="relative column items:end gap">
              ${duration !== 'custom' &&
              html`<ui-input layout="width::16">
                <select value="${duration}" onchange="${html.set('duration')}">
                  <option value="month">Last Month</option>
                  <option value="yesterday">Yesterday</option>
                  <option value="custom">Custom</option>
                </select>
              </ui-input>`}
              ${duration === 'custom' &&
              html`
                <div layout="row gap items:center">
                  <ui-input layout="width:16">
                    <input
                      type="date"
                      value="${dateFrom}"
                      max="${dateTo}"
                      onchange="${html.set('dateFrom')}"
                    />
                  </ui-input>
                  <ui-text>-</ui-text>
                  <ui-input layout="width:16">
                    <input
                      type="date"
                      value="${dateTo}"
                      min="${dateFrom}"
                      onchange="${html.set('dateTo')}"
                    />
                  </ui-input>
                </div>
              `}
              <ui-text type="label-xs" color="tertiary" layout="margin:right">
                ${shortDateFormatter.format(new Date(dateFrom))}
                ${dateTo !== dateFrom &&
                html`- ${shortDateFormatter.format(new Date(dateTo))}`}
              </ui-text>
            </div>
          </div>
        </section>
        ${store.error(mergedStats)}
        ${store.ready(mergedStats) &&
        html`
          <section layout="column gap:2">
            <div layout="column gap">
              <ui-text type="display-s">Facts</ui-text>
              <ui-text type="body-l" mobile-type="body-m" color="secondary">
                Provides an overview of the essential aspects of privacy
                protection.
              </ui-text>
            </div>
            <div
              layout="column gap:2"
              layout@768px="grid:2:2"
              layout@1024px="grid:4:1"
            >
              <ui-card layout="column gap padding:2.5">
                <div layout="row items:center gap">
                  <ui-icon
                    name="websites"
                    color="wtm-secondary"
                    layout="size:6"
                  ></ui-icon>
                  <ui-text type="display-2xl">${mergedStats.pages}</ui-text>
                </div>
                <ui-text type="label-l" color="secondary">
                  Pages visited
                </ui-text>
              </ui-card>
              <ui-card layout="column gap padding:2.5">
                <div layout="row items:center gap">
                  <ui-icon
                    name="block-s"
                    color="danger-primary"
                    layout="size:6"
                  ></ui-icon>
                  <ui-text type="display-2xl">
                    ${mergedStats.trackersBlocked}
                  </ui-text>
                </div>
                <ui-text type="label-l" color="secondary">
                  Trackers blocked
                </ui-text>
              </ui-card>
              <ui-card layout="column gap padding:2.5">
                <div layout="row items:center gap">
                  <ui-icon
                    name="eye"
                    color="brand-primary"
                    layout="size:6"
                  ></ui-icon>
                  <ui-text type="display-2xl">
                    ${mergedStats.trackersModified}
                  </ui-text>
                </div>
                <ui-text type="label-l" color="secondary">
                  Trackers modified
                </ui-text>
              </ui-card>
              ${store.ready(mergedStats.groupedTrackers[0]) &&
              html`
                <ui-action>
                  <a
                    href="${WTM_PAGE_URL}/trackers/${mergedStats
                      .groupedTrackers[0].id}"
                    target="_blank"
                  >
                    <ui-card layout="column gap padding:2.5">
                      <div layout="row items:end gap">
                        <ui-category-icon
                          name="${mergedStats.groupedTrackers[0].category}"
                          size="large"
                        ></ui-category-icon>
                        <ui-text type="display-2xs" layout="row items:center">
                          ${mergedStats.groupedTrackers[0].name}
                          <ui-icon name="chevron-right-s"></ui-icon>
                        </ui-text>
                      </div>
                      <ui-text type="body-m" color="secondary">
                        was the most frequently observed tracker across all web
                        pages visited.
                      </ui-text>
                    </ui-card>
                  </a>
                </ui-action>
              `}
            </div>
          </section>
          <section layout="column gap:2:5" layout@1280px="grid:2:1">
            <div layout="column gap:4" layout@1280px="padding">
              <div layout="column gap">
                <ui-text type="display-s">Observed activities</ui-text>
                <ui-text type="body-l" mobile-type="body-m" color="secondary">
                  Reveals what's hidden beneath the internet’s surface. With
                  WhoTracks.Me, you can uncover the identities behind every
                  tracker.
                </ui-text>
              </div>
              <div layout="column" layout@768px="row gap:2">
                <ui-tracker-wheel
                  categories="${mergedStats.categories}"
                  layout="size:24 self:center margin:4"
                  layout@768px="self:start margin:2"
                ></ui-tracker-wheel>
                <div layout="column grow">
                  ${mergedStats.groupedCategories.map(
                    ({ id, count }) => html`
                      <ui-category
                        name="${id}"
                        count="${count}"
                        large
                      ></ui-category>
                    `,
                  )}
                </div>
              </div>
              <ui-pagination
                layout="column gap"
                layout@768px="grid:2"
                layout@1280px="grid:2:5 height::360px"
              >
                ${mergedStats.groupedTrackers.map(
                  ({ id, name, category }, index) => html`
                    <ui-action>
                      <a href="${WTM_PAGE_URL}/trackers/${id}" target="_blank">
                        <ui-card flat layout="padding row gap items:center">
                          <ui-text
                            type="label-s"
                            layout="block:center width::3"
                          >
                            ${index + 1}
                          </ui-text>
                          <div layout="grow width:0">
                            <ui-text type="label-m" ellipsis>${name}</ui-text>
                            <ui-text type="body-s" color="secondary">
                              ${categories[category]}
                            </ui-text>
                          </div>
                          <ui-category-icon
                            name="${category}"
                          ></ui-category-icon>
                        </ui-card>
                      </a>
                    </ui-action>
                  `,
                )}
              </ui-pagination>
            </div>
            <div layout="column gap:3" layout@1280px="padding">
              <div layout="column gap">
                <ui-text type="display-s">Trends</ui-text>
                <ui-text type="body-l" mobile-type="body-m" color="secondary">
                  Uncovers that no two days are alike. With Ghostery, you’re
                  protected each day.
                </ui-text>
              </div>
              <div layout="grid:3">
                <whotracksme-chart-button
                  active="${trends.includes('pages')}"
                  onclick="${toggleTrend('pages')}"
                >
                  <div layout="row items:center gap">
                    <ui-icon
                      name="websites"
                      color="wtm-secondary"
                      layout="size:2"
                    ></ui-icon>
                    <ui-text type="headline-s">${mergedStats.pages}</ui-text>
                  </div>
                  <ui-text type="label-xs" color="secondary">
                    Pages visited
                  </ui-text>
                </whotracksme-chart-button>
                <whotracksme-chart-button
                  active="${trends.includes('trackersBlocked')}"
                  onclick="${toggleTrend('trackersBlocked')}"
                >
                  <div layout="row items:center gap">
                    <ui-icon
                      name="block-s"
                      color="danger-primary"
                      layout="size:2"
                    ></ui-icon>
                    <ui-text type="headline-s">
                      ${mergedStats.trackersBlocked}
                    </ui-text>
                  </div>
                  <ui-text type="label-xs" color="secondary">
                    Trackers blocked
                  </ui-text>
                </whotracksme-chart-button>
                <whotracksme-chart-button
                  active="${trends.includes('trackersModified')}"
                  onclick="${toggleTrend('trackersModified')}"
                >
                  <div layout="row items:center gap">
                    <ui-icon
                      name="eye"
                      color="brand-primary"
                      layout="size:2"
                    ></ui-icon>
                    <ui-text type="headline-s">
                      ${mergedStats.trackersModified}
                    </ui-text>
                  </div>
                  <ui-text type="label-xs" color="secondary">
                    Trackers modified
                  </ui-text>
                </whotracksme-chart-button>
              </div>
              <whotracksme-chart-line
                dateFrom="${dateFrom}"
                dateTo="${dateTo}"
                trends="${trends}"
                layout="grow"
              ></whotracksme-chart-line>
            </div>
          </section>
          <section layout="block:center margin:0:auto width:::960px">
            <ui-text type="body-l" mobile-type="body-m" color="secondary">
              All information displayed on the WhoTracks.Me Tab or
              <span>
                ${html`<ui-text
                  type="label-l"
                  mobile-type="label-m"
                  color="brand-primary"
                  translate="no"
                  layout="inline"
                >
                  <a href="https://www.ghostery.com/whotracksme">
                    ghostery.com/whotracksme</a
                  ></ui-text
                >`}</span
              >
              is an aggregate of facts about web trackers. These reports power
              Ghostery's anti-tracking technology, protecting the entire
              community.
            </ui-text>
          </section>
        `}
      </main>
    </template>
  `,
};
