/**
 * Application Constants
 *
 * Ghostery Browser Extension
 * https://www.ghostery.com/
 *
 * Copyright 2019 Ghostery, Inc. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0
 */

// panel
export const UPDATE_PANEL_DATA = 'UPDATE_PANEL_DATA';
export const UPDATE_CLIQZ_MODULE_DATA = 'UPDATE_CLIQZ_MODULE_DATA';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const TOGGLE_CLIQZ_FEATURE = 'TOGGLE_CLIQZ_FEATURE';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const TOGGLE_EXPERT = 'TOGGLE_EXPERT';

// summary
export const GET_SUMMARY_DATA = 'GET_SUMMARY_DATA';
export const UPDATE_TRACKER_COUNTS = 'UPDATE_TRACKER_COUNTS';
export const UPDATE_GHOSTERY_PAUSED = 'UPDATE_GHOSTERY_PAUSED';
export const UPDATE_SITE_POLICY = 'UPDATE_SITE_POLICY';
export const FILTER_TRACKERS = 'FILTER_TRACKERS';

// detail
export const TOGGLE_EXPANDED = 'TOGGLE_EXPANDED';

// rewards
export const UPDATE_REWARDS_DATA = 'UPDATE_REWARDS_DATA';
export const TOGGLE_OFFERS_ENABLED = 'TOGGLE_OFFERS_ENABLED';
export const REMOVE_OFFER = 'REMOVE_OFFER';
export const SET_OFFER_READ = 'SET_OFFER_READ';
export const SEND_SIGNAL = 'SEND_SIGNAL';

// blocking
export const UPDATE_BLOCKING_DATA = 'UPDATE_BLOCKING_DATA';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_CATEGORY_BLOCKED = 'UPDATE_CATEGORY_BLOCKED';
export const UPDATE_TRACKER_BLOCKED = 'UPDATE_TRACKER_BLOCKED';
export const UPDATE_TRACKER_TRUST_RESTRICT = 'UPDATE_TRACKER_TRUST_RESTRICT';
export const UPDATE_BLOCK_ALL_TRACKERS = 'UPDATE_BLOCK_ALL_TRACKERS';
export const TOGGLE_EXPAND_ALL = 'TOGGLE_EXPAND_ALL';

// settings
export const IMPORT_SETTINGS_DIALOG = 'IMPORT_SETTINGS_DIALOG';
export const IMPORT_SETTINGS_NATIVE = 'IMPORT_SETTINGS_NATIVE';
export const IMPORT_SETTINGS_FAILED = 'IMPORT_SETTINGS_FAILED';
export const EXPORT_SETTINGS = 'EXPORT_SETTINGS';
export const SELECT_ITEM = 'SELECT_ITEM';
export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';
export const UPDATE_DATABASE = 'UPDATE_DATABASE';
export const UPDATE_NOTIFICATION_STATUS = 'UPDATE_NOTIFICATION_STATUS';
export const UPDATE_SETTINGS_BLOCK_ALL_TRACKERS = 'UPDATE_SETTINGS_BLOCK_ALL_TRACKERS';
export const UPDATE_SETTINGS_CATEGORY_BLOCKED = 'UPDATE_SETTINGS_CATEGORY_BLOCKED';
export const UPDATE_SETTINGS_TRACKER_BLOCKED = 'UPDATE_SETTINGS_TRACKER_BLOCKED';
export const SETTINGS_SEARCH_SUBMIT = 'SETTINGS_SEARCH_SUBMIT';
export const SETTINGS_TOGGLE_EXPAND_ALL = 'SETTINGS_TOGGLE_EXPAND_ALL';
export const SETTINGS_UPDATE_SEARCH_VALUE = 'SETTINGS_UPDATE_SEARCH_VALUE';
export const SETTINGS_FILTER = 'SETTINGS_FILTER';
export const GET_SETTINGS_DATA = 'GET_SETTINGS_DATA';

// subscription
export const SET_THEME = 'SET_THEME';
export const CLEAR_THEME = 'CLEAR_THEME';
