name: Upload builds to release

on:
  release:
    types:
      - prereleased
  workflow_dispatch:

jobs:
  release-v10:
    if: startsWith(github.ref, 'refs/tags/v10')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies in repo root
        run: npm ci
        working-directory: .
      - name: Build packages
        run: npm run package -- --simple

      - name: Upload Firefox build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: web-ext-artifacts/ghostery-firefox.zip
          asset_name: ghostery-firefox-${{ env.VERSION }}.zip
          asset_content_type: application/gzip

      - name: Upload Chromium build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: web-ext-artifacts/ghostery-chromium.zip
          asset_name: ghostery-chromium-${{ env.VERSION }}.zip
          asset_content_type: application/gzip
