name: Upload builds to release

on:
  release:
    types:
      - prereleased
  workflow_dispatch:

jobs:
  release-v10:
    if: startsWith(github.ref, 'refs/tags/v10')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies in repo root
        run: npm ci
        working-directory: .
      - name: Build packages
        run: npm run package -- --simple

      - name: Upload Firefox build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: web-ext-artifacts/ghostery-firefox.zip
          asset_name: ghostery-firefox-${{ env.VERSION }}.zip
          asset_content_type: application/gzip

      - name: Upload Chromium build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: web-ext-artifacts/ghostery-chromium.zip
          asset_name: ghostery-chromium-${{ env.VERSION }}.zip
          asset_content_type: application/gzip

      - name: Download source code archives
        run: |
          curl -L -o "ghostery-extension-${{ env.VERSION }}.zip" "https://github.com/${{ github.repository }}/archive/refs/tags/v${{ env.VERSION }}.zip"
          curl -L -o "ghostery-extension-${{ env.VERSION }}.tar.gz" "https://github.com/${{ github.repository }}/archive/refs/tags/v${{ env.VERSION }}.tar.gz"

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
          echo "trust-model always" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "default-cache-ttl 3600" >> ~/.gnupg/gpg-agent.conf
          echo "max-cache-ttl 7200" >> ~/.gnupg/gpg-agent.conf
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --passphrase-fd 0 --sign --local-user 7541C764E251DA408BD645A2F8A0BDD7B2021F1E /dev/null

      - name: Export GPG public key
        run: |
          gpg --export --armor 7541C764E251DA408BD645A2F8A0BDD7B2021F1E > ghostery-gpg-public-key.asc

      - name: Create PGP signatures
        run: |
          gpg --detach-sign --armor --local-user 7541C764E251DA408BD645A2F8A0BDD7B2021F1E "ghostery-extension-${{ env.VERSION }}.zip"
          gpg --detach-sign --armor --local-user 7541C764E251DA408BD645A2F8A0BDD7B2021F1E "ghostery-extension-${{ env.VERSION }}.tar.gz"

      - name: Upload PGP signature for zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ghostery-extension-${{ env.VERSION }}.zip.asc
          asset_name: ghostery-extension-${{ env.VERSION }}.zip.asc
          asset_content_type: text/plain

      - name: Upload PGP signature for tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ghostery-extension-${{ env.VERSION }}.tar.gz.asc
          asset_name: ghostery-extension-${{ env.VERSION }}.tar.gz.asc
          asset_content_type: text/plain

      - name: Upload GPG public key
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ghostery-gpg-public-key.asc
          asset_name: ghostery-gpg-public-key.asc
          asset_content_type: text/plain
