name: Test Extenision Manifest V2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-mv2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension-manifest-v2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies in repo root
        run: npm ci
        working-directory: .
      - name: Build Licenses
        run: |
          npm run licenses
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test
      - name: Build
        run: npm run build.prod
