name: Test Extenision Manifest V2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-mv2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension-manifest-v2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18'
          cache-dependency-path: ./extension-manifest-v2/package-lock.json
      - name: Install dependencies in libs
        run: npm ci
        working-directory: libs
      - name: Install dependencies in ui
        run: npm ci
        working-directory: ui
      - name: Install dependencies
        run: |
          npm ci
      - name: Build Licenses
        run: |
          node ./tools/licenses/fetchLicenses.js
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test

