name: Linting & code style in packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies in repo root
        run: npm ci
        working-directory: .
      - name: packages/libs
        run: npm test
        working-directory: packages/libs
      - name: packages/trackers-preview
        run: npm test
        working-directory: packages/trackers-preview
      - name: packages/ui
        run: npm test
        working-directory: packages/ui
