name: Test Extenision Manifest V3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-mv3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension-manifest-v3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies in repo root
        run: npm ci
        working-directory: .
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
