/**
 * Rewards Component
 *
 * Ghostery Browser Extension
 * https://www.ghostery.com/
 *
 * Copyright 2018 Ghostery, Inc. All rights reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0
 */

import React, { Component } from 'react';
import { Link, Route } from 'react-router-dom';
import { ToggleSlider, RewardListItem, RewardDetail } from './BuildingBlocks';

/**
 * @class The Rewards Panel shows offers generated by Ghostery Rewards.
 * The panel is opened from a button in the Detailed View's footer.
 * See DetailMenu.jsx.
 * @memberof PanelClasses
 */
class Rewards extends React.Component {
	constructor(props) {
		super(props);

		// event bindings
		this.toggleRewards = this.toggleRewards.bind(this);
		this.removeReward = this.removeReward.bind(this);

		this.renderRewardListComponent = this.renderRewardListComponent.bind(this);
		this.renderRewardDetailComponent = this.renderRewardDetailComponent.bind(this);
	}

	/**
	 * Lifecycle event
	 */
	componentDidMount() {
		if (this.props.rewardsActive && !this.props.rewards) {
			this.props.actions.getActiveRewards();
		}
	}

	/**
	 * Handles toggling rewards on/off
	 */
	toggleRewards() {
		const { rewardsActive } = this.props;
		this.props.actions.showNotification({
			text: `Ghostery Rewards is ${rewardsActive ? 'OFF' : 'ON'}`,
			classes: 'purple',
		});
		this.props.actions.toggleRewardsActive();
	}

	/**
	 * Handles removing a reward from the Rewards array
	 * @param  {Int} id the ID of the reward
	 */
	removeReward(id) {
		this.props.actions.removeReward(id);
	}

	/**
	 * Helper render function for the Rewards Header
	 * @return {JSX} JSX for the Rewards Header
	 */
	renderRewardsHeader() {
		const { rewardsActive, location } = this.props;
		const showBack = location.pathname.indexOf('/detail/rewards/detail') !== -1;
		const showToggle = location.pathname === '/detail/rewards/list';

		return (
			<div className="RewardsPanel__header flex-container align-center-middle">
				{showBack && (
					<Link to="/detail/rewards/list" className="RewardsPanel--send-left RewardsPanel--add-padding flex-container clickable">
						<svg height="18" width="12" fill="none" stroke="#4a4a4a" strokeWidth="3" strokeLinecap="round">
							<path d="M10,2L2,9L10,16" />
						</svg>
					</Link>
				)}
				<span className="RewardsPanel__title">{ t('panel_detail_rewards_title') }</span>
				{showToggle && (
					<span className="RewardsPanel--send-right flex-container align-middle">
						<span>{rewardsActive ? 'ON ' : 'OFF '}</span>
						<ToggleSlider
							className="RewardsPanel--add-padding display-inline-block"
							isChecked={rewardsActive}
							onChange={this.toggleRewards}
						/>
					</span>
				)}
			</div>
		);
	}

	/**
	 * Helper render function for the list of Rewards Items
	 * @return {JSX} JSX for the Rewards Items List
	 */
	renderRewardListComponent() {
		const { rewards, rewardsActive } = this.props;
		if (!rewardsActive) {
			return <span>Rewards Not Active</span>;
		} else if (!rewards) {
			return <span>Loading Rewards ...</span>;
		} else if (rewards.length === 0) {
			return <span>No Rewards Were Found</span>;
		}

		const rewardsList = rewards.map((reward, index) => (
			<RewardListItem
				index={index}
				id={reward.id}
				key={reward.id}
				unread={reward.unread}
				text={reward.text}
				expires={reward.expires}
				clickCloseButton={this.removeReward}
			/>
		));
		return <div className="RewardsPanel__scroll_content">{ rewardsList }</div>;
	}

	/**
	 * Helper render function for an individual Reward Item
	 * @return {JSX} JSX for the Rewards Detail Item
	 */
	renderRewardDetailComponent(routeProps) {
		const { id } = routeProps.match.params;
		const reward = this.props.rewards.find(el => el.id === +id);

		return (
			<RewardDetail
				id={reward.id}
				code={reward.code}
				description={reward.description}
				expires={reward.expires}
				actions={this.props.actions}
			/>
		);
	}

	/**
	 * React's required render function. Returns JSX
	 * @return {JSX} JSX for rendering the Rewards portion of the Detailed View
	 */
	render() {
		return (
			<div className="RewardsPanel">
				{this.renderRewardsHeader()}
				<Route path="/detail/rewards/list" render={this.renderRewardListComponent} />
				<Route path="/detail/rewards/detail/:id" render={this.renderRewardDetailComponent} />
			</div>
		);
	}
}

export default Rewards;
